project:
  type: website
  resources: assets
website:
  title: "David Almona"
  navbar:
    background: "#000000"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.pdf
        text: Resumé
        target: blank
      - href: cv.pdf
        text: CV
        target: blank
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/davidalmona/
        target: blank
      - icon: github
        href: https://github.com/almonadavid
        target: blank
      - icon: twitter-x
        href: https://x.com/almondanalysis
        target: blank
      - icon: file-pdf
        href: cv.pdf
        target: blank
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    link-external-newwindow: true
execute:
  freeze: auto