project:
  type: website
  resources: assets

website:
  title: "David Almona"
  navbar:
    background: "#000000"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/davidalmona/
        target: blank # open in new tab
      - icon: cash
        href: https://venmo.com/
        target: blank
      - icon: github
        href: https://github.com/almonadavid
        target: blank
      - icon: file-pdf
        href: assets/David Almona, Resume.pdf
        target: blank

format:
  html:
    theme: quartz
      - cosmos
    css: styles.css
    toc: true

execute: 
  freeze: auto


