project:
  type: website
  resources: assets

website:
  title: "David Almona"
  navbar:
    background: "#000000" 
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: assets/David Almona, Resume.pdf
        text: Résumé
        target: blank
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/davidalmona/
        target: blank
      - icon: github
        href: https://github.com/almonadavid
        target: blank
      - icon: file-pdf
        href: assets/David Almona, Resume.pdf
        target: blank

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true
    link-external-newwindow: true

execute: 
  freeze: auto


