project:
  type: website
  resources: assets

website:
  title: "David Almona"
  navbar:
    background: "#000000" 
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/davidalmona/
        target: blank # open in new tab
        title: "LinkedIn""
      - icon: github
        href: https://github.com/almonadavid
        target: blank
        title: "GitHub"
      - icon: file-pdf
        href: assets/David Almona, Resume.pdf
        target: blank
        title: "View Resume"

format:
  html:
    theme: quartz
      - cosmos
    css: styles.css
    toc: true
    link-external-newwindow: true

execute: 
  freeze: auto


