---
---


### Education
**Centre College**, Danville, KY  <br>
BS in Economics & Finance, Data Science minor | *Expected May 2026*

**College for Social Innovation**, Boston, MA <br>
Semester in the City (SITC) Fellow | *Aug 2025 - Dec 2025*
Advisor: [Emily Lagas](https://www.linkedin.com/in/emily-lagas-lcsw/)

**African Leadership Academy**, Johannesburg, South Africa  <br>
Cambridge A Levels: Physics and Mathematics | *2020 - 2022*


### Experience
**Business Program Development Fellow** | Sustainable Business Network of Massachusetts <br>
*Sep 2025 - Dec 2025* <br>
Supervisor: [Kerry Kokkinogenis ](https://www.linkedin.com/in/kerry-kokkinogenis-95a92724/)

**Undergraduate Research Fellow** | Carnegie Mellon University  <br>
*Jun 2025 - Jul 2025*  <br>
Advisors: [Quang Nguyen](https://www.linkedin.com/in/qntkhvn/), [Daniel Wicker](https://www.linkedin.com/in/daniel-wicker/) (Charlotte FC)

**Data Analytics: Qualitative & Quantitative Insights Externship** | Beats by Dre  <br> 
*Mar 2025 - June 2025*  

**Undergraduate Research** | Centre College  <br>
*Sep 2024 - Nov 2024*<br>
Advisor: [Jeffrey Heath](https://www.linkedin.com/in/jeffrey-heath-3294598/)


### Conferences Attended
**Carnegie Mellon Sports Analytics Conference** | Pittsburgh, PA  
*Oct 2025* | In-person

**SABR Analytics Conference** | Phoenix, AZ  
*Mar 2025* | Virtual attendance

**Carnegie Mellon Sports Analytics Conference** | Pittsburgh, PA  
*Nov 2024* | In-person